apiVersion: v1
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    port 1883
    listener 9001
    protocol websockets
    autosave_interval 300
    log_dest file /mosquitto/log/mosquitto.log
    persistence true
    persistence_location /mosquitto/data/
    user mosquitto
    
kind: ConfigMap