kind: Service
apiVersion: v1
metadata:
  name: mosquitto-mqtt
spec:
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
    name: mqtt
---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-ws
spec:
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
    name: ws
---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-wss
spec:
  selector:
    app: mosquitto
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
    name: wss
