apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuoreweb
  labels:
    app: cuoreweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuoreweb
  template:
    metadata:
      labels:
        app: cuoreweb
    spec:
      containers:
      - name: cuoreweb
        image: victorrpt/cuore_web:latest # here specify the image
        ports:
        - containerPort: 3000
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: cuoreweb-http
spec:
  selector:
    app: cuoreweb
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
apiVersion: v1
---
kind: Service
metadata:
  name: cuoreweb
spec:
  selector:
    app: cuoreweb
  ports:
    - port: 8080
      targetPort: 3000
      name: http
  type: LoadBalancer 